# These are supported funding model platforms

github: [HydroFarmerJason]
patreon: phalplatform
open_collective: phal
ko_fi: phalplatform
custom: ["https://phal.io/donate", "https://phal.io/enterprise"]
