version: '3.8'

services:
  # PHAL API Server
  phal-api:
    build: ./backend
    container_name: phal-api
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
    env_file:
      - .env
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
      - ./certs:/app/certs:ro
    depends_on:
      - postgres
      - redis
      - influxdb
    networks:
      - phal-network

  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: phal-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: phal
      POSTGRES_USER: phal
      POSTGRES_PASSWORD: ${DB_PASSWORD:-phal}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - phal-network

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: phal-redis
    restart: unless-stopped
    command: redis-server --appendonly yes
    volumes:
      - redis-data:/data
    networks:
      - phal-network

  # InfluxDB Time Series Database
  influxdb:
    image: influxdb:2.7-alpine
    container_name: phal-influxdb
    restart: unless-stopped
    ports:
      - "8086:8086"
    environment:
      INFLUXDB_DB: phal
      INFLUXDB_ADMIN_USER: admin
      INFLUXDB_ADMIN_PASSWORD: ${INFLUX_PASSWORD:-admin}
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - influxdb-config:/etc/influxdb2
    networks:
      - phal-network

  # Grafana (Optional)
  grafana:
    image: grafana/grafana:latest
    container_name: phal-grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_PASSWORD:-admin}
      GF_INSTALL_PLUGINS: grafana-clock-panel,grafana-simple-json-datasource
    volumes:
      - grafana-data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    depends_on:
      - influxdb
    networks:
      - phal-network

  # MQTT Broker (Optional)
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: phal-mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ./mosquitto/config:/mosquitto/config
      - mosquitto-data:/mosquitto/data
      - mosquitto-logs:/mosquitto/log
    networks:
      - phal-network

  # Nginx Reverse Proxy
  nginx:
    image: nginx:alpine
    container_name: phal-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./frontend:/usr/share/nginx/html:ro
      - ./certs:/etc/nginx/certs:ro
    depends_on:
      - phal-api
    networks:
      - phal-network

volumes:
  postgres-data:
  redis-data:
  influxdb-data:
  influxdb-config:
  grafana-data:
  mosquitto-data:
  mosquitto-logs:

networks:
  phal-network:
    driver: bridge
